namespace IRETP.Web.Services;

/// <summary>
/// Lightweight in-memory translation registry for the IRETP web portal.
/// Keyed by a short slug (e.g. "nav.dashboard"); returns the translation for the
/// requested language or falls back to the key itself if unknown.
/// Designed so adding extended-phase languages is a single dictionary insert.
/// </summary>
public class LocalizationService
{
    private readonly UiStateService _ui;

    public LocalizationService(UiStateService ui)
    {
        _ui = ui;
    }

    public string this[string key] => Translate(key);

    public string Translate(string key, string? language = null)
    {
        var lang = language ?? _ui.Language;
        if (_map.TryGetValue(lang, out var dict) && dict.TryGetValue(key, out var value))
            return value;
        if (_map["en"].TryGetValue(key, out var en))
            return en;
        return key;
    }

    public string Direction => _ui.IsRtl ? "rtl" : "ltr";

    private static readonly Dictionary<string, Dictionary<string, string>> _map = new()
    {
        ["en"] = new()
        {
            // Navigation
            ["nav.dashboard"] = "Dashboard",
            ["nav.publicPortal"] = "Public Portal",
            ["nav.investor"] = "Investor",
            ["nav.map"] = "Interactive Map",
            ["nav.priceIndex"] = "Price Index",
            ["nav.rentalIndex"] = "Rental Index",
            ["nav.transactions"] = "Transactions",
            ["nav.projects"] = "Projects",
            ["nav.developers"] = "Developers",
            ["nav.scorecards"] = "Scorecards",
            ["nav.analytics"] = "Analytics",
            ["nav.compare"] = "Compare",
            ["nav.aiAgent"] = "AI Agent",
            ["nav.greti"] = "GRETI Progress",
            ["nav.watchlist"] = "Watchlist",
            ["nav.alerts"] = "Alerts",
            ["nav.apiPortal"] = "Open Data API",
            ["nav.admin"] = "Administration",
            ["nav.adminHub"] = "Administration Hub",
            ["nav.ewrs"] = "EWRS Dashboard",
            ["nav.escrow"] = "Escrow Monitoring",
            ["nav.developerRating"] = "Developer Rating",
            ["nav.cms"] = "Content Management",
            ["nav.notifications"] = "Notifications",
            ["nav.login"] = "Login",
            ["nav.logout"] = "Logout",
            ["nav.register"] = "Register",
            // Common
            ["common.loading"] = "Loading…",
            ["common.export"] = "Export",
            ["common.apply"] = "Apply",
            ["common.reset"] = "Reset",
            ["common.search"] = "Search",
            ["common.cancel"] = "Cancel",
            ["common.save"] = "Save",
            ["common.close"] = "Close",
            ["common.delete"] = "Delete",
            ["common.back"] = "Back",
            ["common.next"] = "Next",
            ["common.previous"] = "Previous",
            // Dashboard
            ["dashboard.welcome"] = "Welcome to IRETP",
            ["dashboard.subtitle"] = "Integrated Real Estate Transparency Platform — Dubai Land Department",
            ["dashboard.totalVolume"] = "Total Sales Volume",
            ["dashboard.totalTransactions"] = "Total Transactions",
            ["dashboard.avgPricePerSqft"] = "Avg Price / Sq Ft",
            ["dashboard.topRegion"] = "Top Region",
            ["dashboard.topAreas"] = "Top 5 Areas",
            ["dashboard.topDevelopers"] = "Top 5 Developers",
            ["dashboard.interactiveMap"] = "Interactive Map",
            ["dashboard.mapDesc"] = "Explore Dubai areas in 3D with live metrics",
            ["dashboard.txnDesc"] = "Browse sales and mortgage records",
            ["dashboard.analyticsDesc"] = "Area and developer rankings",
            // Market charts (FR-004)
            ["dashboard.asOf"] = "Data as of",
            ["dashboard.marketCharts"] = "Market Charts",
            ["dashboard.monthlyVolume"] = "Monthly Transaction Volume",
            ["dashboard.typeBreakdown"] = "Ready vs Off-Plan",
            ["dashboard.topZones"] = "Top 5 Most-Active Zones",
            ["dashboard.psfTrend"] = "Price/Sqft vs Volume",
            ["dashboard.transactions"] = "Transactions",
            ["common.custom"] = "Custom",
            // Unit
            ["unit.sqft"] = "sqft",
            ["unit.aed"] = "AED",
        },
        ["ar"] = new()
        {
            ["nav.dashboard"] = "لوحة المعلومات",
            ["nav.publicPortal"] = "البوابة العامة",
            ["nav.investor"] = "المستثمر",
            ["nav.map"] = "الخريطة التفاعلية",
            ["nav.priceIndex"] = "مؤشر الأسعار",
            ["nav.rentalIndex"] = "مؤشر الإيجارات",
            ["nav.transactions"] = "المعاملات",
            ["nav.projects"] = "المشاريع",
            ["nav.developers"] = "المطورون",
            ["nav.scorecards"] = "بطاقات الأداء",
            ["nav.analytics"] = "التحليلات",
            ["nav.compare"] = "مقارنة",
            ["nav.aiAgent"] = "المساعد الذكي",
            ["nav.greti"] = "تتبع مؤشر GRETI",
            ["nav.watchlist"] = "قائمة المتابعة",
            ["nav.alerts"] = "التنبيهات",
            ["nav.apiPortal"] = "بوابة البيانات المفتوحة",
            ["nav.admin"] = "الإدارة",
            ["nav.adminHub"] = "مركز الإدارة",
            ["nav.ewrs"] = "نظام الإنذار المبكر",
            ["nav.escrow"] = "مراقبة حسابات الضمان",
            ["nav.developerRating"] = "تقييم المطورين",
            ["nav.cms"] = "إدارة المحتوى",
            ["nav.notifications"] = "الإشعارات",
            ["nav.login"] = "تسجيل الدخول",
            ["nav.logout"] = "تسجيل الخروج",
            ["nav.register"] = "إنشاء حساب",
            ["common.loading"] = "جارٍ التحميل…",
            ["common.export"] = "تصدير",
            ["common.apply"] = "تطبيق",
            ["common.reset"] = "إعادة تعيين",
            ["common.search"] = "بحث",
            ["common.cancel"] = "إلغاء",
            ["common.save"] = "حفظ",
            ["common.close"] = "إغلاق",
            ["common.delete"] = "حذف",
            ["common.back"] = "رجوع",
            ["common.next"] = "التالي",
            ["common.previous"] = "السابق",
            ["dashboard.welcome"] = "مرحبًا بك في IRETP",
            ["dashboard.subtitle"] = "منصة الشفافية العقارية المتكاملة — دائرة الأراضي والأملاك بدبي",
            ["dashboard.totalVolume"] = "إجمالي قيمة المبيعات",
            ["dashboard.totalTransactions"] = "إجمالي المعاملات",
            ["dashboard.avgPricePerSqft"] = "متوسط السعر/قدم مربع",
            ["dashboard.topRegion"] = "أعلى منطقة",
            ["dashboard.topAreas"] = "أعلى ٥ مناطق",
            ["dashboard.topDevelopers"] = "أعلى ٥ مطورين",
            ["dashboard.interactiveMap"] = "الخريطة التفاعلية",
            ["dashboard.mapDesc"] = "استكشف مناطق دبي ثلاثية الأبعاد مع مقاييس مباشرة",
            ["dashboard.txnDesc"] = "تصفح سجلات البيع والرهن العقاري",
            ["dashboard.analyticsDesc"] = "تصنيفات المناطق والمطورين",
            ["dashboard.asOf"] = "البيانات حتى",
            ["dashboard.marketCharts"] = "الرسوم البيانية للسوق",
            ["dashboard.monthlyVolume"] = "حجم المعاملات الشهرية",
            ["dashboard.typeBreakdown"] = "جاهز مقابل على الخارطة",
            ["dashboard.topZones"] = "أكثر ٥ مناطق نشاطًا",
            ["dashboard.psfTrend"] = "السعر/قدم² مقابل الحجم",
            ["dashboard.transactions"] = "المعاملات",
            ["common.custom"] = "مخصص",
            ["unit.sqft"] = "قدم²",
            ["unit.aed"] = "درهم",
        },

        // -------------------------------------------------------------------
        // Phase 4 extended languages (RFP Section 7). Navigation + common
        // strings scaffold in Phase 4; full page-level translations are keyed
        // in by the DLD content team via the CMS after go-live.
        // -------------------------------------------------------------------
        ["zh"] = new()
        {
            ["nav.dashboard"] = "仪表盘",
            ["nav.publicPortal"] = "公共门户",
            ["nav.investor"] = "投资者",
            ["nav.map"] = "互动地图",
            ["nav.priceIndex"] = "价格指数",
            ["nav.rentalIndex"] = "租赁指数",
            ["nav.transactions"] = "交易",
            ["nav.projects"] = "项目",
            ["nav.developers"] = "开发商",
            ["nav.scorecards"] = "评分卡",
            ["nav.compare"] = "比较",
            ["nav.analytics"] = "数据分析",
            ["nav.aiAgent"] = "AI 助手",
            ["nav.greti"] = "GRETI 进度",
            ["nav.watchlist"] = "关注列表",
            ["nav.alerts"] = "提醒",
            ["nav.apiPortal"] = "开放数据 API",
            ["nav.notifications"] = "通知",
            ["nav.login"] = "登录",
            ["nav.logout"] = "退出",
            ["nav.register"] = "注册",
            ["common.loading"] = "加载中…",
            ["common.export"] = "导出",
            ["common.apply"] = "应用",
            ["common.search"] = "搜索",
            ["common.cancel"] = "取消",
            ["common.save"] = "保存",
            ["common.close"] = "关闭",
            ["common.reset"] = "重置",
            ["common.delete"] = "删除",
            ["common.back"] = "返回",
            ["common.next"] = "下一步",
            ["common.previous"] = "上一步",
            ["dashboard.welcome"] = "欢迎使用 IRETP",
            ["dashboard.subtitle"] = "综合房地产透明度平台 — 迪拜土地局",
            ["dashboard.totalVolume"] = "总销售额",
            ["dashboard.totalTransactions"] = "总交易数",
            ["dashboard.avgPricePerSqft"] = "平均每平方英尺价格",
            ["dashboard.topRegion"] = "热门区域",
            ["dashboard.topAreas"] = "热门 5 大区域",
            ["dashboard.topDevelopers"] = "热门 5 大开发商",
            ["dashboard.interactiveMap"] = "互动地图",
            ["dashboard.mapDesc"] = "通过实时指标探索迪拜区域",
            ["dashboard.txnDesc"] = "浏览销售和按揭记录",
            ["dashboard.analyticsDesc"] = "区域和开发商排名",
            ["unit.sqft"] = "平方英尺",
            ["unit.aed"] = "迪拉姆",
        },
        ["ru"] = new()
        {
            ["nav.dashboard"] = "Панель управления",
            ["nav.publicPortal"] = "Публичный портал",
            ["nav.investor"] = "Инвестор",
            ["nav.map"] = "Интерактивная карта",
            ["nav.priceIndex"] = "Индекс цен",
            ["nav.rentalIndex"] = "Индекс аренды",
            ["nav.transactions"] = "Сделки",
            ["nav.projects"] = "Проекты",
            ["nav.developers"] = "Застройщики",
            ["nav.scorecards"] = "Оценочные карты",
            ["nav.compare"] = "Сравнение",
            ["nav.analytics"] = "Аналитика",
            ["nav.aiAgent"] = "ИИ-агент",
            ["nav.greti"] = "Прогресс GRETI",
            ["nav.watchlist"] = "Избранное",
            ["nav.alerts"] = "Оповещения",
            ["nav.apiPortal"] = "Открытые данные API",
            ["nav.notifications"] = "Уведомления",
            ["nav.login"] = "Вход",
            ["nav.logout"] = "Выход",
            ["nav.register"] = "Регистрация",
            ["common.loading"] = "Загрузка…",
            ["common.export"] = "Экспорт",
            ["common.apply"] = "Применить",
            ["common.search"] = "Поиск",
            ["common.cancel"] = "Отмена",
            ["common.save"] = "Сохранить",
            ["common.close"] = "Закрыть",
            ["common.reset"] = "Сброс",
            ["common.delete"] = "Удалить",
            ["common.back"] = "Назад",
            ["common.next"] = "Далее",
            ["common.previous"] = "Предыдущий",
            ["dashboard.welcome"] = "Добро пожаловать в IRETP",
            ["dashboard.subtitle"] = "Интегрированная платформа прозрачности недвижимости — Департамент земли Дубая",
            ["dashboard.totalVolume"] = "Общий объём продаж",
            ["dashboard.totalTransactions"] = "Всего сделок",
            ["dashboard.avgPricePerSqft"] = "Средняя цена за кв. фут",
            ["dashboard.topRegion"] = "Лидирующий район",
            ["dashboard.topAreas"] = "Топ 5 районов",
            ["dashboard.topDevelopers"] = "Топ 5 застройщиков",
            ["dashboard.interactiveMap"] = "Интерактивная карта",
            ["dashboard.mapDesc"] = "Изучайте районы Дубая с актуальными показателями",
            ["dashboard.txnDesc"] = "Просматривайте записи о продажах и ипотеке",
            ["dashboard.analyticsDesc"] = "Рейтинги районов и застройщиков",
            ["unit.sqft"] = "кв. фут",
            ["unit.aed"] = "AED",
        },
        ["ur"] = new()
        {
            ["nav.dashboard"] = "ڈیش بورڈ",
            ["nav.publicPortal"] = "عوامی پورٹل",
            ["nav.investor"] = "سرمایہ کار",
            ["nav.map"] = "انٹرایکٹو نقشہ",
            ["nav.priceIndex"] = "قیمت انڈیکس",
            ["nav.rentalIndex"] = "کرایہ انڈیکس",
            ["nav.transactions"] = "لین دین",
            ["nav.projects"] = "پراجیکٹس",
            ["nav.developers"] = "ڈویلپرز",
            ["nav.scorecards"] = "اسکور کارڈز",
            ["nav.compare"] = "موازنہ",
            ["nav.analytics"] = "تجزیات",
            ["nav.aiAgent"] = "اے آئی ایجنٹ",
            ["nav.greti"] = "GRETI پیش رفت",
            ["nav.watchlist"] = "واچ لسٹ",
            ["nav.alerts"] = "الرٹس",
            ["nav.apiPortal"] = "اوپن ڈیٹا API",
            ["nav.notifications"] = "اطلاعات",
            ["nav.login"] = "لاگ ان",
            ["nav.logout"] = "لاگ آؤٹ",
            ["nav.register"] = "رجسٹر",
            ["common.loading"] = "لوڈ ہو رہا ہے…",
            ["common.export"] = "برآمد",
            ["common.apply"] = "لاگو کریں",
            ["common.search"] = "تلاش",
            ["common.cancel"] = "منسوخ",
            ["common.save"] = "محفوظ",
            ["common.close"] = "بند",
            ["common.reset"] = "ری سیٹ",
            ["common.delete"] = "حذف",
            ["common.back"] = "واپس",
            ["common.next"] = "اگلا",
            ["common.previous"] = "پچھلا",
            ["dashboard.welcome"] = "IRETP میں خوش آمدید",
            ["dashboard.subtitle"] = "مربوط ریئل اسٹیٹ شفافیت پلیٹ فارم — دبئی لینڈ ڈیپارٹمنٹ",
            ["dashboard.totalVolume"] = "کل فروخت حجم",
            ["dashboard.totalTransactions"] = "کل لین دین",
            ["dashboard.avgPricePerSqft"] = "اوسط قیمت فی مربع فٹ",
            ["dashboard.topRegion"] = "سرفہرست علاقہ",
            ["dashboard.topAreas"] = "سرفہرست 5 علاقے",
            ["dashboard.topDevelopers"] = "سرفہرست 5 ڈویلپرز",
            ["dashboard.interactiveMap"] = "انٹرایکٹو نقشہ",
            ["dashboard.mapDesc"] = "لائیو میٹرکس کے ساتھ دبئی کے علاقوں کو دریافت کریں",
            ["dashboard.txnDesc"] = "فروخت اور مارگیج ریکارڈز دیکھیں",
            ["dashboard.analyticsDesc"] = "علاقہ اور ڈویلپر درجہ بندی",
            ["unit.sqft"] = "مربع فٹ",
            ["unit.aed"] = "درہم",
        },
        ["fr"] = new()
        {
            ["nav.dashboard"] = "Tableau de bord",
            ["nav.publicPortal"] = "Portail public",
            ["nav.investor"] = "Investisseur",
            ["nav.map"] = "Carte interactive",
            ["nav.priceIndex"] = "Indice des prix",
            ["nav.rentalIndex"] = "Indice locatif",
            ["nav.transactions"] = "Transactions",
            ["nav.projects"] = "Projets",
            ["nav.developers"] = "Promoteurs",
            ["nav.scorecards"] = "Fiches d'évaluation",
            ["nav.compare"] = "Comparer",
            ["nav.analytics"] = "Analyses",
            ["nav.aiAgent"] = "Agent IA",
            ["nav.greti"] = "Progrès GRETI",
            ["nav.watchlist"] = "Liste de suivi",
            ["nav.alerts"] = "Alertes",
            ["nav.apiPortal"] = "API données ouvertes",
            ["nav.notifications"] = "Notifications",
            ["nav.login"] = "Connexion",
            ["nav.logout"] = "Déconnexion",
            ["nav.register"] = "Inscription",
            ["common.loading"] = "Chargement…",
            ["common.export"] = "Exporter",
            ["common.apply"] = "Appliquer",
            ["common.search"] = "Rechercher",
            ["common.cancel"] = "Annuler",
            ["common.save"] = "Enregistrer",
            ["common.close"] = "Fermer",
            ["common.reset"] = "Réinitialiser",
            ["common.delete"] = "Supprimer",
            ["common.back"] = "Retour",
            ["common.next"] = "Suivant",
            ["common.previous"] = "Précédent",
            ["dashboard.welcome"] = "Bienvenue sur IRETP",
            ["dashboard.subtitle"] = "Plateforme intégrée de transparence immobilière — Département foncier de Dubaï",
            ["dashboard.totalVolume"] = "Volume total des ventes",
            ["dashboard.totalTransactions"] = "Total des transactions",
            ["dashboard.avgPricePerSqft"] = "Prix moyen au pied carré",
            ["dashboard.topRegion"] = "Région en tête",
            ["dashboard.topAreas"] = "Top 5 des zones",
            ["dashboard.topDevelopers"] = "Top 5 des promoteurs",
            ["dashboard.interactiveMap"] = "Carte interactive",
            ["dashboard.mapDesc"] = "Explorez les zones de Dubaï avec des indicateurs en direct",
            ["dashboard.txnDesc"] = "Parcourez les registres de ventes et d'hypothèques",
            ["dashboard.analyticsDesc"] = "Classements des zones et promoteurs",
            ["unit.sqft"] = "pi²",
            ["unit.aed"] = "AED",
        },
        ["hi"] = new()
        {
            ["nav.dashboard"] = "डैशबोर्ड",
            ["nav.publicPortal"] = "सार्वजनिक पोर्टल",
            ["nav.investor"] = "निवेशक",
            ["nav.map"] = "इंटरैक्टिव मानचित्र",
            ["nav.priceIndex"] = "मूल्य सूचकांक",
            ["nav.rentalIndex"] = "किराया सूचकांक",
            ["nav.transactions"] = "लेनदेन",
            ["nav.projects"] = "परियोजनाएँ",
            ["nav.developers"] = "डेवलपर्स",
            ["nav.scorecards"] = "स्कोरकार्ड",
            ["nav.compare"] = "तुलना करें",
            ["nav.analytics"] = "विश्लेषण",
            ["nav.aiAgent"] = "एआई एजेंट",
            ["nav.greti"] = "GRETI प्रगति",
            ["nav.watchlist"] = "वॉचलिस्ट",
            ["nav.alerts"] = "अलर्ट",
            ["nav.apiPortal"] = "ओपन डेटा API",
            ["nav.notifications"] = "सूचनाएँ",
            ["nav.login"] = "लॉगिन",
            ["nav.logout"] = "लॉगआउट",
            ["nav.register"] = "पंजीकरण",
            ["common.loading"] = "लोड हो रहा है…",
            ["common.export"] = "निर्यात",
            ["common.apply"] = "लागू करें",
            ["common.search"] = "खोजें",
            ["common.cancel"] = "रद्द",
            ["common.save"] = "सहेजें",
            ["common.close"] = "बंद",
            ["common.reset"] = "रीसेट",
            ["common.delete"] = "हटाएं",
            ["common.back"] = "वापस",
            ["common.next"] = "अगला",
            ["common.previous"] = "पिछला",
            ["dashboard.welcome"] = "IRETP में आपका स्वागत है",
            ["dashboard.subtitle"] = "एकीकृत रियल एस्टेट पारदर्शिता मंच — दुबई भूमि विभाग",
            ["dashboard.totalVolume"] = "कुल बिक्री मात्रा",
            ["dashboard.totalTransactions"] = "कुल लेनदेन",
            ["dashboard.avgPricePerSqft"] = "औसत मूल्य प्रति वर्ग फुट",
            ["dashboard.topRegion"] = "शीर्ष क्षेत्र",
            ["dashboard.topAreas"] = "शीर्ष 5 क्षेत्र",
            ["dashboard.topDevelopers"] = "शीर्ष 5 डेवलपर्स",
            ["dashboard.interactiveMap"] = "इंटरैक्टिव मानचित्र",
            ["dashboard.mapDesc"] = "लाइव मेट्रिक्स के साथ दुबई क्षेत्रों का अन्वेषण करें",
            ["dashboard.txnDesc"] = "बिक्री और बंधक रिकॉर्ड ब्राउज़ करें",
            ["dashboard.analyticsDesc"] = "क्षेत्र और डेवलपर रैंकिंग",
            ["unit.sqft"] = "वर्ग फुट",
            ["unit.aed"] = "दिरहम",
        },
        ["de"] = new()
        {
            ["nav.dashboard"] = "Dashboard",
            ["nav.publicPortal"] = "Öffentliches Portal",
            ["nav.investor"] = "Investor",
            ["nav.map"] = "Interaktive Karte",
            ["nav.priceIndex"] = "Preisindex",
            ["nav.rentalIndex"] = "Mietindex",
            ["nav.transactions"] = "Transaktionen",
            ["nav.projects"] = "Projekte",
            ["nav.developers"] = "Entwickler",
            ["nav.scorecards"] = "Bewertungskarten",
            ["nav.compare"] = "Vergleichen",
            ["nav.analytics"] = "Analysen",
            ["nav.aiAgent"] = "KI-Assistent",
            ["nav.greti"] = "GRETI-Fortschritt",
            ["nav.watchlist"] = "Beobachtungsliste",
            ["nav.alerts"] = "Benachrichtigungen",
            ["nav.apiPortal"] = "Open-Data-API",
            ["nav.notifications"] = "Mitteilungen",
            ["nav.login"] = "Anmelden",
            ["nav.logout"] = "Abmelden",
            ["nav.register"] = "Registrieren",
            ["common.loading"] = "Laden…",
            ["common.export"] = "Exportieren",
            ["common.apply"] = "Anwenden",
            ["common.search"] = "Suchen",
            ["common.cancel"] = "Abbrechen",
            ["common.save"] = "Speichern",
            ["common.close"] = "Schließen",
            ["common.reset"] = "Zurücksetzen",
            ["common.delete"] = "Löschen",
            ["common.back"] = "Zurück",
            ["common.next"] = "Weiter",
            ["common.previous"] = "Zurück",
            ["dashboard.welcome"] = "Willkommen bei IRETP",
            ["dashboard.subtitle"] = "Integrierte Immobilientransparenz-Plattform — Grundbuchamt Dubai",
            ["dashboard.totalVolume"] = "Gesamtverkaufsvolumen",
            ["dashboard.totalTransactions"] = "Gesamttransaktionen",
            ["dashboard.avgPricePerSqft"] = "Ø-Preis pro Quadratfuß",
            ["dashboard.topRegion"] = "Top-Region",
            ["dashboard.topAreas"] = "Top-5-Gebiete",
            ["dashboard.topDevelopers"] = "Top-5-Entwickler",
            ["dashboard.interactiveMap"] = "Interaktive Karte",
            ["dashboard.mapDesc"] = "Entdecken Sie Dubai mit Live-Kennzahlen",
            ["dashboard.txnDesc"] = "Verkaufs- und Hypothekendaten durchsuchen",
            ["dashboard.analyticsDesc"] = "Bereichs- und Entwickler-Rankings",
            ["unit.sqft"] = "ft²",
            ["unit.aed"] = "AED",
        }
    };
}
